### ISSUE TITLE
UI, allow end user to turn on/off arbitrary sets of agencies. 

### ISSUE THREAD

**Issue by ed-g** [ODOT-PTS/TNExT#13]
Add capacity at UI for end user to turn on/off arbitrary sets of agencies. When an agency is turned off it would not be reflected in any reporting or mapping. An example of a use of this functionality would be for ODOT to turn on all agencies that receive 5311 funding and run reports … like the statewide report. Adding this functionality in combination with the import UI, gives us most of the capacity of the playground. It looks like this class of functionality is currently implemented pre-database build in the import UI, is it practical to use queries to achieve same result, without an extended db build process?

**Comment by ODOT-RPTD-mb** [comment]
Will require extensive testing, since this will touch most or all queries.

**Comment by ed-g** [comment]
When agencies are "turned off" for reporting purposes is it OK if they are turned off for _every_ user of the tool at that time?

If so then one possibility is to create a filtered version of each table and run queries on those -- the query text would not need to change only the table it is querying against.

If we want each user to have their own "view" of the data a similar process is possible but a little more work since we'd need to associate a set of tables per user/session.

**Comment by ed-g** [comment]
@srinivas13794 or @BenFields724 would you be able to create a javascript user interface to "turn off" agencies in the main page, and that sends that list to a Java server page?

If there is a Java server page that knows which agencies should be currently turned off or on, I can create the database backend to actually turn them off or on.

**Comment by ODOT-RPTD-mb** [comment]
@ed-g @srinivas13794 @BenFields724  Each user should have their own view of the data.

**Comment by ed-g** [comment]
@srinivas13794 @BenFields724 how are users tracked within java? Is there a JSP session ID or similar?

**Comment by srinivas13794** [comment]
@ed-g  I have been working on a javascript interface to the functionality you have mentioned.I will push the code and let you know once I have finished it.Again for this task too if we could discuss it briefly over a conference call it would be helpful.

**Comment by ed-g** [comment]
This is notes from the call. If you can get some list of "hidden" agency id's to java, I can update the table, and then modify a few queries to test the process.

Then if those test queries work we can modify the rest of the queries to be compatible with this way of hiding agencies.

**Comment by ed-g** [comment]
@srinivas13794 @BenFields724 any updates on this?

**Comment by srinivas13794** [comment]
I have pushed a version of this interface onto your development server.I
still need to make a few changes.

**Comment by ed-g** [comment]
Is this under the "FS" button?

**Comment by srinivas13794** [comment]
Yes.

**Comment by srinivas13794** [comment]
@ed-g As I mentioned yesterday I have added a basic interface for user selection of agencies that can be accessed by clicking on the FS button.I have programmed it in such a way that the agencyid's are sent to the backend.This is done in the /feedselect path under the queries.java file.I have also added a Print statement that prints out the agencyid's it should show up on your logs.

**Comment by ed-g** [comment]
Tie into back end such that java/sql side "knows" which agencies the current user has selected. 4 hours.

Design a way to include this information on the sql side in a way that is both performant and easy to join against. 4-6 hours.

Add the join to every query. Depends on the method chosen. 20 minutes to 1 hour per query depending on complexity.

**Comment by ODOT-RPTD-mb** [comment]
@irees @drewda @PPaulsonOregonDOT 
It should be relatively easy for user to understand which agencies are active/inactive. Indication of active agencies should be part of report metadata file.

Let's experiment first with the "Statewide Extended Report".

**Comment by irees** [comment]
@ODOT-RPTD-mb  @PPaulsonOregonDOT @drewda 

I have an initial implementation and a demo on one report. I used the Transit Agencies Summary Report because it clearly shows the results of the selection.

http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/AgenSReport.html?&dbindex=12&popYear=2010

I used an approach very similar to what @ed-g sketched out above. There is a new `user_selected_agencies` table, where each user can set their list of visible agencies, editable using a widget based on the design of the main map agency selector. The results are sent to the `/setHiddenAgencies` endpoint. The `/Agencyget` endpoint now also returns the visibility of each agency.

This will be relatively easy to add to the rest of the queries, because it's a drop-in replacement for the existing query from `gtfs_selected_feeds`, which is already present in most queries, e.g.:

```
with aids as (select distinct agency_id as aid from gtfs_selected_feeds where username=?)
```
->
```
with aids as (SELECT a.id AS aid FROM gtfs_agencies AS a LEFT OUTER JOIN user_selected_agencies AS b ON (b.username = ? AND a.id = b.agency_id) WHERE b.hidden IS NOT true ORDER BY a.defaultid)
```

Let me know if this design works well and I'll start rolling it out to other queries.

Current limitations: Everyone is using the `admin` user, but this will be replaced with unique sessions in the next update. Also I will improve the agency picker dialog placement and scrolling, and add buttons to "select all / unselect all".

**Comment by irees** [comment]
@PPaulsonOregonDOT

OK. Yes, it reloads the current page, since changing the selection will change the report output. In this regard it works similarly to changing the database selector or the population year selector. I could omit this behavior and require a manual "submit" action. 

It will be pretty easy to change the style of the selector. That can continue to be done now or in the future, so I will start adding the agency filtering and widgets to more reports today.
