### ISSUE TITLE
Agency Extended Report

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#145]
Add area/density metrics to agency extended reports. See issue #17 for more detail.

**Comment by irees** [comment]
Considerations:

1. Service closest to the date of capture is considered most reliable, decreasing with reliability in the future. Service before capture date is reliable.
2. How to handle a feed that may have service cuts vs its highest level of service
3. How to measure seasonal feeds

Keep an eye on: RVTD, ski services, shuttles

Goal: a week with the highest confidence that the representation is accurate.

Possible idea: use middle of identified week as default date for reports in this database.

**Comment by irees** [comment]
I have both of these PRs up on staging. I fixed many issues with the Agency Extended Report queries in general, and added the density report. It has the exact same format and values as the other density report I added for geographic area queries.

Some examples:

agency - basic report
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/AgenXReport.html?&agency=TRIMET&x=0.25&l=2&n=eas&dbindex=12&popYear=2010&areaid=null&type=0&username=admin&geotype=-1&geoid=null&nav=stateS-agencyS

agency - county report
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/AgenXReport.html?&agency=TRIMET&x=0.25&l=2&n=eas&dbindex=12&popYear=2010&areaId=41051&type=0&username=admin&geotype=-1&geoid=null&nav=stateS-countyS-agencyS

agency - census tract report
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/AgenXReport.html?&agency=TRIMET&x=0.25&l=2&n=eas&dbindex=12&popYear=2010&areaId=41051009000&type=1&username=admin&geotype=-1&geoid=null&nav=stateS-countyS-tractS-agencyS

agency - congressional district report
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/AgenXReport.html?&agency=TRIMET&x=0.25&l=2&n=eas&dbindex=0&popYear=2010&areaId=4101&type=5&username=admin&geotype=-1&geoid=null&nav=stateS-congS-agencyS

**Comment by PPaulsonOregonDOT** [comment]
@irees I loaded each of these reports, and the reports in general look good, but the census tract report brings up an important issue. If you scroll through that report, there are a number of density metrics for rural areas that show with entries of N/A. 

For this census tract, that result makes sense, because there are 0 rural stops, meaning that this must be an urban Census Tract. The problem is that as far as I could tell, neither the report or the metadata provide any indication of which census block I am investigating. This appears to be limited to the transit agency reports, because if you look at the top left hand corner of the report below, it (and the metadata created when the report is exported) provides information about the Congressional District, Agency, and Route that were selected to generate this stops report.

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/stopreport.html?agency=101&x=0.25&route=455&n=art&popYear=2010&nav=stateS-congS-route&areaid=4101&type=5&dbindex=13

In testing this issue, the path by which you reach the transit agencies extended report does not appear impact the occurrence of the issue,

**Comment by irees** [comment]
@PPaulsonOregonDOT Hi, yes, I noticed the same issue. It shows the overall path of the report but does not list what specific thing you are looking at. You have to remember from where you opened the window. Can you make a new issue for this?
