### ISSUE TITLE
Sept 2018 GTFS snapshot staging report failures

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#148]
Multiple reports complete with "no data available" messages. For example: https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoCongDistsReport.html?&dbindex=13&popYear=2010 

Statewide summary report does not complete in reasonable time.

**Comment by PPaulsonOregonDOT** [comment]
In looking at those reports, it appears that the no data available could be related to the 0/0 feed selected parameter. in the top right of the right report. Given further investigation, it looks like the data is just missing, because I was expecting a similar result from this report https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoCountiesReport.html?&dbindex=12&popYear=2010 with 0 feeds selected. This results in the tool using the parameter of 0/56 feed, which varies from the above reports.

**Comment by irees** [comment]
Looking into this now.

**Comment by irees** [comment]
@PPaulsonOregonDOT I fixed this manually in `september2018` and added a code fix for future database. Can you take a look? https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoCongDistsReport.html?&dbindex=13&popYear=2010

**Comment by PPaulsonOregonDOT** [comment]
@irees The tool has data from 70 agencies/60 feeds in the reports that I use for testing, so this issue appears to be resolved.
