### ISSUE TITLE
more "employees served" (WAC) than population?

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#152]
Can this be valid? Does it represent a data issue?

noticed when reviewing key transit hubs export Sept. 2018 db

**Comment by anniekfifer** [comment]
Example: https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/KeyHubSreport.html?&x1=0.08&x2=0.25&x3=2.0&n=iwt&dbindex=13&popYear=2010

**Comment by PPaulsonOregonDOT** [comment]
This issue is being addressed as part of a bigger effort ongoing effort to update all of the population data that is loaded into TNExT. I don't think that this issue can/should be addressed prior to that update, but should be retained on this page as an open issue to serve as documentation for new/returning users that it is a known issue that we're working on.
