### ISSUE TITLE
Refinement Key Transit Hubs Report Methodology

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#161]
Comparing the Key Transit Hubs Report and the Transit Hub Report sorted to hubs with Agencies County > 3, there are additional hubs that would reasonably fit our definition of a Key Transit Hub, but are not being identified in the KTH report. I suspect that this is a result of a selection made to eliminate hubs that serve services which are wholly contained within a connecting agency's service area. A refinement of how TNEXT makes this selection would be helpful in meeting the policy goals of this report.

**Comment by ODOT-RPTD-mb** [comment]
the prudent path with this report might be to remove as a report option.

**Comment by anniekfifer** [comment]
@ODOT-RPTD-mb Can you elaborate on what refinements might be explored here, and/or provide examples of hubs that should be considered key hubs that currently don't fit the criteria?

>Comparing the Key Transit Hubs Report and the Transit Hub Report sorted to hubs with Agencies County > 3

Just to make sure I understand, I'm not seeing conditions on the number of counties. I am seeing that the number of agencies in the hub needs to be over three, is that what is meant by this?

**Comment by anniekfifer** [comment]
@ODOT-RPTD-mb pinging about these refinements, before Thursday would be great so I can get an estimate ready

**Comment by ODOT-RPTD-mb** [comment]
@anniekfifer Here are some specific examples of issue.
[KTH Discrepancy List.xlsx](https://github.com/ODOT-PTS/TNExT/files/5100339/KTH.Discrepancy.List.xlsx)

**Comment by ODOT-RPTD-mb** [comment]
Revised version, replacing "Transit Network Report" with "Transit Hub Report" text.
[KTH Discrepancy List.xlsx](https://github.com/ODOT-PTS/TNExT/files/5105774/KTH.Discrepancy.List.xlsx)

**Comment by anniekfifer** [comment]
The key transit hub report is counting feeds in the cluster instead of agencies -- for example, hubs with Albany Transit System, Linn-Benton Loop and Linn Shuttle are counted as two-agency hubs because Albany Transit System and Linn-Benton Loop are in the same feed. Fixing this would take less than 2 hours.

**Comment by anniekfifer** [comment]
@ODOT-RPTD-mb Apologies for a late follow-up here -- One hub that isn't accounted for by my proposed/estimated fix above is the Canby/Woodburn/Cherriots hub. The reason that's not included in the Key Hub report is because Woodburn is "contained" geographically by Cherriots and is thus not counted when deciding if the cluster is a key hub. 

Let me know if you think that it's an error that Woodburn is considered to be contained by Cherriots, or if you think this hub and similar hubs should still be counted as key hubs and I can follow up quickly with an estimate adjustment

**Comment by ODOT-RPTD-sh** [comment]
With the need to otherwise refine hubs eligible to be KTH, ODOT will plan to use the Transit Hubs report and manually refine that list (per the attached) rather than use the TNExT KTH Report to ensure ongoing accuracy of ODOT's KTH list.
[About ODOT's Key-Transit-Hubs - 2020.docx](https://github.com/ODOT-PTS/TNExT/files/5295219/About.ODOT.s.Key-Transit-Hubs.-.2020.docx)
.

**Comment by anniekfifer** [comment]
Hi @ODOT-RPTD-sh, sorry I hadn't looked over the document in your comment earlier. The "Process for Identifying Key Transit Hubs" steps look similar to tnext's report -- clusters served by <3 non-containing services (with services corrected in this issue fix to be agencies rather than GTFS feeds) are filtered out of the TH report. Were there additional refinements used not listed there, or was the tnext report not providing those refinements accurately (outside of the known problem in this issue)?
