### ISSUE TITLE
Aggregated Urban Area Extended Report, pop served @ level of service problem

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#186]
Population served at level of service values for aggregated urban area extended report are too low.  (employment and other results may also be off...)

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUrbansXreport.html?&areaid=71317&x=0.25&l=64&n=izs&dbindex=13&popYear=2010&geotype=-1&geoid=null&nav=stateS-urbanS 
Urban Area Extended Report: [these numbers look reasonable]
•	Portland, OR – WA urbanized area (1,849,898)
o	Sept 2018-GTFS, 2010-pop, 2-LOS
o	26 Sept 2018 selected
o	% pop served: 57.99%
o	% pop served @ LOS 2: 57.99%
o	% pop served @ LOS 64: 32.13%

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUrbansRXreport.html?&popMin=1500000&popMax=2000000&x=0.25&l=64&n=izs&dbindex=13&popYear=2010&nav=stateS-AggUAS 
Aggregated Urban Area (Summary - Extended) Reports:
•	Pop range 1,500,000 to 1,849,898
•	Sept 2018-GTFS, 2010-pop, 2-LOS
•	26 Sept 2018 selected
•	% of pop served: 58.02%
•	% of pop served at LOS 2: 4.26% [LOS of service values are clearly wrong]
•	% of pop served at LOS 64: .04%

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/AgenXReport.html?&agency=TRIMET&x=0.25&l=2&n=izs&dbindex=13&popYear=2010&areaid=null&type=0&username=admin&geotype=-1&geoid=null&nav=stateS-agencyS 
Transit Agency Extended Report:
•	TriMet
•	Sept 2018-GTFS, 2010-pop, 2-LOS
•	Urban pop served at level of service: 1,048,122
•	Rural pop served at level of service: 2,834
•	So TriMet alone serves 56.81% (1,050,956/1,849,898) of Aggregated Urban area above @ LOS [and aggregated urban area extended report shows 4.26% @ LOS 2]

**Comment by PPaulsonOregonDOT** [comment]
I checked this report in the May 2018 report, with the day set to today, and it provides perfectly reasonable results:

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUrbansRXreport.html?&popMin=1500000&popMax=2000000&x=0.25&l=2&n=dbt&dbindex=12&popYear=2010&nav=stateS-AggUAS

but if I run the report for May 16th, 2018, the report demonstrates the behavior noted above:

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUrbansRXreport.html?&popMin=1500000&popMax=2000000&x=0.25&l=2&n=eps&dbindex=12&popYear=2010&nav=stateS-AggUAS

I had been working under the impression that this issue was a result of the visit counts being counted incorrectly, which caused a significant number of stops not to be included in the population calculations. However, if you run the Key Transit Hubs report for May 16th out of the May 2018 database, pioneer square has 17,000 visits. This makes me think that either the LOS reports aren't being passed the visit data that the KTH report is, perhaps because there's a mismatch between how the LOS calculation is being passed the date, which would reduce the population served at LOS by excluding feeds were active during the dates in question. Is it possible that the level of service metric calculation is attributed to the census blocks themselves and the way that this calculation is being made is causing an error?

**Comment by ODOT-RPTD-mb** [comment]
@anniekfifer Note that this issue is also Very High Importance.

**Comment by PPaulsonOregonDOT** [comment]
It appears that this problem has gotten worse/more pronounced in the July 2019 Snaphot.

The TRIMET report shows a significant number of people served at LOS = 2 and 62, and the Portland Urban areas shows 58% and 32%, respectively. However, if you look at the aggregated urbanized areas with population greater than 1 million, it is zeroed out at LOS = 2

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUrbansRXreport.html?&popMin=1000000&popMax=2000000&x=0.25&l=2&n=gjt&dbindex=16&popYear=2010&nav=stateS-AggUAS

**Comment by ODOT-RPTD-mb** [comment]
Using the same July 10th date and looking at urban area extended report for Portland, results look reasonable for LOS = 2.
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUrbansXreport.html?&areaid=71317&x=0.25&l=2&n=gjt&dbindex=16&popYear=2010&geotype=-1&geoid=null&nav=stateS-urbanS

**Comment by PPaulsonOregonDOT** [comment]
As an additional note, this issue appears to be limited the aggregated urban areas report, because the county extended reports for this region appear normal (Clackamas, Multnomah and Washington, referenced below)

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoCountiesXreport.html?&areaid=41051&x=0.25&l=2&n=gjt&dbindex=16&popYear=2010&nav=stateS-countyS

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoCountiesXreport.html?&areaid=41005&x=0.25&l=2&n=gjt&dbindex=16&popYear=2010&nav=stateS-countyS

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoCountiesXreport.html?&areaid=41067&x=0.25&l=2&n=jct&dbindex=16&popYear=2010&nav=stateS-countyS

This issue does not appear to be limited to the Portland urbanized area. I ran the aggregated urbanized area extended report for urban areas with population between 75,000 and 1 million (which  includes Medford, Salem, Eugene and Bend, but excludes Portland) and had the same issue:

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUrbansRXreport.html?&popMin=75000&popMax=1000000&x=0.25&l=2&n=gjt&dbindex=16&popYear=2010&nav=stateS-AggUAS

Of potential interest is that the aggregated urban area SUMMARY report demonstrates a recognition of the geographic boundary, because shows a variable number of stops based on the bounds placed on the population by the user)

75,000- 1 million (2,572 stops)
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUAreasRReport.html?&popMin=75000&popMax=1000000&dbindex=16&popYear=2010#

75,000-2 million people (10,643 stops)
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUAreasRReport.html?&popMin=75000&popMax=2000000&dbindex=16&popYear=2010

However, this number (2,572 and 10,643) does not match the stop totals from the four areas that compose this slice of urban areas (2,487, 10,527) from the reports below. Could this be related to the double counting of stops we saw in issue #200? 

75k to 1 million
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUAreasReport.html?&popMin=75000&uc=3&popMax=1000000&dbindex=16&popYear=2010&type=3&nav=stateS-AggUAS#

75k to 2 million
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoUAreasReport.html?&popMin=75000&uc=3&popMax=2000000&dbindex=16&popYear=2010&type=3&nav=stateS-AggUAS#

**Comment by anniekfifer** [comment]
This report was not getting the dbindex parameter at all and was defaulting to dbindex 0, which is Summer 2015 on staging and production. I don't see any reason why this wouldn't have been occurring for a while, so it's possible that this report has been running on dbindex 0 behind the scenes for a long time.

@ODOT-RPTD-mb @PPaulsonOregonDOT FYI

**Comment by anniekfifer** [comment]
Staging is updated with this fix

**Comment by anniekfifer** [comment]
@ODOT-RPTD-mb I logged 3 hours 53 minutes on this issue
