### ISSUE TITLE
Lack of feedback on GTFS database build process

### ISSUE THREAD

**Issue by ODOT-RPTD-mb** [ODOT-PTS/TNExT#188]
Trillium reports zero positive or negative feedback during database build process. Probably two perspectives on process output. 1) Information for staff creating new database, included info leading to understanding of reason for build failure. 2) Information for software debugging purposes.

**Comment by thomastrillium** [comment]
@evantrillium  do you have any specifics from Kalon about what database build issues were encountered? I can look at his email if not.

**Comment by anniekfifer** [comment]
@evantrillium ping

**Comment by evantrillium** [comment]
Question I have:

1) What does a database build failure look like? Is this referring to staging or production?
or another way,
2) Are we referencing the July staging build, and if so, what was considered the failure there?

I know we initially had questions about deactivating dbs, but once that was cleared as okay, we were able to move forward without issue per our documentation, which we updated at that time.

**Comment by anniekfifer** [comment]
>What does a database build failure look like?

Not sure! I think that's the information that would be helpful to retrieve from Kalon's experiences with database build failures. Maybe @ed-g has insight on this?

>Is this referring to staging or production?

Staging I think -- the database is built before it's used by staging, and its simply restored to production after that. I think this issue is referring to the process that is initiated by clicking "Add a New Database" here http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/admin

> Are we referencing the July staging build, and if so, what was considered the failure there?
 
Nope, this is just for build failures in general

**Comment by evantrillium** [comment]
Okay - I am unaware of any current issues with db build fails, and I did...7?...of them for July. I will keep in mind that I/data tech team need to provide details about fails, should they happen, going forward.

**Comment by ed-g** [comment]
Agree the context would help. I do know that the first tnext database I put together ... I was very confused. I wonder a simple documentation update would help the user know what to expect.
