### ISSUE TITLE
Documentation for calculation and algorithms.

### ISSUE THREAD

**Issue by ed-g** [ODOT-PTS/TNExT#21]
Are we missing: how calculated, measured, algorithm descriptions… if so create missing content. [Phil check new Wiki page for descriptions, as well as tool tips and metadata]

**Comment by ed-g** [comment]
Assign to Phil

**Comment by ed-g** [comment]
For use by planners and GIS analysts who work with transit data.

**Comment by ed-g** [comment]
@PPaulsonOregonDOT here's a naive work plan I put together. Any suggested changes?

* Identify the algorithms used, which we'd like to document.
* For each algorithm
  * Make a page in the wiki with description, and also include tool tips here
  * Create github issue for each recommended tooltip

**Comment by PPaulsonOregonDOT** [comment]
I think that the difficulty/time required for this depends on how much knowledge you assume a general planner/GIS analyst is going to want/need to know about the individual SQL queries.

**Comment by ed-g** [comment]
Could we find a planner who would be willing to give us a a half-hour of their time reviewing the docs and giving us guidance?

Otherwise just as a guess I'd tend to lean towards "assume they're good at GIS but not familiar with specifics of our table layout".

**Comment by pouyalireza** [comment]
@ed-g  I think  it might be more appropriate @PPaulsonOregonDOT to tag this task.As from the point of view of the user we need to identify what information might need to be added to the wiki.

**Comment by PPaulsonOregonDOT** [comment]
Does someone have a link to the development version of the wiki? It would be helpful for this task to be able to point planners here to provide feedback?

**Comment by pouyalireza** [comment]
@PPaulsonOregonDOT here is the link:  http://tnasoftwaretool.engr.oregonstate.edu:8080/TNAtoolAPI-Webapp/wiki#!index.md

**Comment by ed-g** [comment]
FYI I've been collecting these links on 

https://github.com/pouyalireza/TNAST_MAVEN/wiki

**Comment by ODOT-RPTD-mb** [comment]
- I suspect the following are not documented in tool tips or in a location otherwise easily available to end users:
- How is population/employment assigned to stop buffers 
- How is stop clustering done, how stable are clusters as cluster radius changes
- How is data at the census tract level disaggregated to the block level
- How are population projections created, How do future populations relate to urbanized areas, i.e. are new urbanized areas created with future populations or are pop changes combined with current area definitions
- Pop served at level of service; how does served at level of service handle situations where multiple stops "serve" the same block, can visits by the same run/trip be counted more than once, if more than one stop for the same trip is within the area of interest
- When do results include service/results outside of Oregon
- Meaning  of missing or red agencies in agency list drop down
- Other areas...

**Comment by ODOT-RPTD-mb** [comment]
Getting to documentation on listed issues will require information from OSU team or Trillium.

**Comment by PPaulsonOregonDOT** [comment]
I generally agree with the points made above, though I think the assignment of population/employment and the population served at level of service documentation are implemented pretty well in the tool,and that the issue about census block aggregation/dissaggregation may not be feasible in the tool.

I would suggest that most of this information be included in the User Manual that is included in the wiki for the tool. One general improvement I would like to see with the User Manual is to have it transferred from an PDF into an HTML or similar format, where the table of contents consists of hyperlinks to the specific sections, which I think would improve the ability of users to quickly find information.

**Comment by ODOT-RPTD-mb** [comment]
ODOT need to clearly define work for Trillium if any.

**Comment by PPaulsonOregonDOT** [comment]
@ed-g, am I correct in thinking that the Level of Service attribute is a derivative of the visits for a given stop? My understanding from talking to Dr. Porter was that the visits to a given stop were calculated, and then excluded from any further analysis if they weren't visited X times.
