### ISSUE TITLE
June 2020 Database Agency Summary Report contains 0 Agencies

### ISSUE THREAD

**Issue by philip-paulson-ibigroup** [ODOT-PTS/TNExT#238]
Selecting the statewide summary report for June 2020 shows that there are 67 agencies operating in the state:
https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/GeoStateSreport.html?&dbindex=31&popYear=2010#

However, if you navigate to the transit agencies summary report using the hyperlink in the report above or through the OTA Agencies Floating window, no data is present:

https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/AgenSReport.html?&x=0.25&dbindex=31&popYear=2010&nav=stateS

Relevantly, the agency data dump report returns data for the Data Dump report

**Comment by anniekfifer** [comment]
@ODOT-RPTD-sh I believe this can be closed, the report above works for me now: https://oregon-staging.tnext.io/TNAtoolAPI-Webapp/AgenSReport.html?&x=0.25&dbindex=31&popYear=2010&nav=stateS

The underlying cause is issue #241 , but I was able to manually fix the problem entry in the database to get the report back up. Data dump report on staging looks good to me also.
