### ISSUE TITLE
Routes Report not refereshing

### ISSUE THREAD

**Issue by PPaulsonOregonDOT** [ODOT-PTS/TNExT#82]
Working in the tool, @ODOT-RPTD-mb  and I noted that the routes summary report appears not to be refreshing or updating when dates are changed using the date selector. For instance, the report defaults to a today (2/15/17 in this case), but I tried to draw a report for a week of service from the 12/10-12/16 3018 and upon submitting the new dates, the report didn't change. This behavior is similar to what we experienced with the stops report in #32.

**Comment by PPaulsonOregonDOT** [comment]
As a follow-up, clicking on the stops hyperlink from the routes summary reports takes the user to a stop report that doesn't load any time information and hangs up while loading. Reaching the stops report via other reports (agencies summary report, county summary report) does not cause this error, which suggests that something on the routes summary report page itself broken.

**Comment by ODOT-RPTD-mb** [comment]
These issues have not changed in new staging instance of tool.

**Comment by irees** [comment]
@ODOT-RPTD-mb can you provide the url of the exact report

**Comment by ODOT-RPTD-mb** [comment]
@irees 
**Routes Summary Report, date selection issues example:**
http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/routereport.html?&areaid=41001&type=0&x=0.25&n=chs&dbindex=10&popYear=2010&geotype=-1&geoid=null&nav=stateS-countyS#

**Stops Report does not load example:**
http://tna.trilliumtransit.com:8080/TNAtoolAPI-Webapp/stopreport.html?agency=59&x=0.25&route=5228&n=chs&popYear=2010&nav=stateS-countyS-route&areaid=41001&type=0&dbindex=10

**Comment by irees** [comment]
@ODOT-RPTD-mb 

I see the issue you're describing with the Routes Summary Report not refreshing when changing dates. It appears to be a front-end issue.

The Stops Report not loading is due to a 404 error on an API request.

http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/queries/transit/StopsR?agency=59&day=03/08/2018&route=5228&x=0.25&areaid=41001&type=0&key=0.8764877102309176&dbindex=10&popYear=2010&username=admin&geotype=NaN&geoid=null&rc=null&stime=null&etime=null

It looks like it's an issue with the query params, because removing the params "geotype" and after results in a 500 error, not a 404. I'll see what is going on.

**Comment by irees** [comment]
Moving the Stops Report issue to #100

**Comment by PPaulsonOregonDOT** [comment]
It looks like this problem has been diagnosed but not fixed in the most recent version of the tool that I have been looking at. In case it provides some insight about a possible solution, the report I'm looking at is: 
http://tna.trilliumtransit.com:8090/TNAtoolAPI-Webapp/routereport.html?&agency=148&x=0.25&n=cts&dbindex=11&popYear=2010&nav=stateS-agencyS

**Comment by irees** [comment]
The Routes Report not refreshing cause is fairly simple - the "Submit" button is not clickable, so the `onclick` event handler is never fired to call `reloadPage()`. A fix is coming soon.

**Comment by irees** [comment]
The culprit turned out to be an invisible jquery-ui tooltip rendered over the "Submit" button. I changed the positioning of the tooltip so that it won't obscure the Submit button. Alternatively I can remove the jquery-ui tooltips entirely and rely on the browser's built-in tooltip behavior for input elements. PR coming.
